server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/wallet-service/**
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/authorization/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/