CREATE TABLE IF NOT EXISTS WALLETS(
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    CPF VARCHAR(14),
    EMAIL VARCHAR(100),
    BALANCE DECIMAL(10,2)
);

CREATE UNIQUE INDEX IF NOT EXISTS CPF_ID ON WALLETS (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS EMAIL_ID ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS(
    ID SERIAL PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    "VALUE" DECIMAL(10,2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS (ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS (ID)
)
